### ISSUE TITLE
SIP 2 - Eliminate Base64URL Storage Bloat

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#781]
```yaml
  SIP: 2
  Upgrade-Type: Hard Fork (to guarantee outcomes)
  Title: Eliminate Base64URL Storage Bloat
  Author: Orie Steele <orie@transmute.industries>
  Comments-Summary: No comments yet.
  Comments-URI: https://github.com/decentralized-identity/sidetree/sips/2.md
  Status: Draft
  Created: 2020-06-30
```

## Summary

Base64URL is used throughout sidetree, in many cases, as a substitute for canonicalization...

## Motivation

"Although Base64 is a relatively efficient way of encoding binary data it will, on average still increase the file size for more than 25%."

## Requirements

Data structure file size should be minimized.

## Technical Proposal

Replace Base64URL with JCS.
